# Configuration file version
apiVersion: 1

# List of data sources to delete from the database.
deleteDatasources:
  - name: InfluxDB
    orgId: 1

# Mark provisioned data sources for deletion if they are no longer in a provisioning file.
# It takes no effect if data sources are already listed in the deleteDatasources section.
prune: true

# List of data sources to insert/update depending on what's
# available in the database.
datasources:
  # <string, required> Sets the name you use to refer to
  # the data source in panels and queries.
  - name: InfluxDB
    # <string, required> Sets the data source type.
    type: influxdb
    # <string, required> Sets the access mode, either
    # proxy or direct (Server or Browser in the UI).
    # Some data sources are incompatible with any setting
    # but proxy (Server).
    access: proxy
    # <int> Sets the organization id. Defaults to orgId 1.
    orgId: 1
    # <string> Sets a custom UID to reference this
    # data source in other parts of the configuration.
    # If not specified, Grafana generates one.
    uid: influxdb
    # <string> Sets the data source's URL, including the
    # port.
    url: http://influxdb:8086
    # <string> Sets the database name, if necessary.
    database: "$INFLUXDB_DB"
    # <string> Sets the database user, if necessary.
    user: "$INFLUXDB_ADMIN_USER"
    # <string> Sets the database password, if necessary.
    basicAuth:
    # <string> Sets the basic authorization username.
    basicAuthUser:
    # <bool> Enables credential headers.
    withCredentials:
    # <bool> Toggles whether the data source is pre-selected
    # for new panels. You can set only one default
    # data source per organization.
    isDefault:
    # <map> Fields to convert to JSON and store in jsonData.
    jsonData:
      timeInterval: "5s"
    secureJsonData:
      # <string> Sets the database password, if necessary.
      password: "$INFLUXDB_ADMIN_PASSWORD"
    version: 1
    # <bool> Allows users to edit data sources from the
    # Grafana UI.
    editable: false